services:
  wavelength:
    image: ${DOCKER_REGISTRY-}wavelength
    build:
      context: .
      dockerfile: Wavelength/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:80
      - Cors_AllowedOrigins=${CORS_ALLOWED_ORIGINS}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Secret=${JWT_SECRET}
    ports:
      - "8080:80"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"