services:
  wavelength:
    image: ${DOCKER_REGISTRY-}wavelength
    build:
      context: .
      dockerfile: Wavelength/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"