services:
  wavelength:
    image: ${DOCKER_REGISTRY-}wavelengthapi
    build:
      context: .
      dockerfile: Wavelength/Dockerfile
    container_name: wavelength-api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:80
      - Cors__AllowedOrigins=${CORS_ALLOWED_ORIGINS}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Secret=${JWT_SECRET}
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
      - Aes__Key=${AES_KEY}
      - Smtp__Host=${SMTP_HOST}
      - Smtp__Port=${SMTP_PORT}
      - Smtp__From=${SMTP_FROM}
      - Smtp__Address=${SMTP_ADDRESS}
      - Smtp__Username=${SMTP_USERNAME}
      - Smtp__Password=${SMTP_PASSWORD} 
      - Smtp__EnableSsl=${SMTP_ENABLE_SSL}
    ports:
      - "${HTTP_PORT}:80"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"