services:
  wavelength:
    image: ${DOCKER_REGISTRY-}wavelength
    build:
      context: .
      dockerfile: Wavelength/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    restart: unless-stopped